### ISSUE TITLE
How to avoid login prompt to login to edge

### ISSUE THREAD

**Issue by mcapitanio** [edge/archive.edge.network#1]
Actually when you have to login to the the edge you have to use:

```console
foo@bar:~$ edge-cli login -u "email@address.com"
```
Is it possible to specify password using env variable or other way in order to avoid the prompt login?

**Comment by Segflow** [comment]
We introduced the `--password-file` flag in edge-cli 1.2

Save your password in a file (say password.txt) and login using:
```
edge-cli login -u email@address.com --password-file password.txt
```
